name: f14k
description: "My first Flutter project and it's about Formula One."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.19.0
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true